"""Data Platform public facade with lazy, backwards-compatible symbol exports.

Importing a lightweight submodule no longer loads the whole extraction engine.
Existing `from arvectum_data import Symbol` and `import *` remain supported.
"""
from __future__ import annotations

from importlib import import_module as _import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .acquisition import (
        AcquisitionAttempt,
        AcquisitionEngine,
        AcquisitionError,
        AcquisitionRequest,
        AcquisitionResult,
        DefaultRenderPolicy,
        HTTPTransport,
        MissingBrowserDependencyError,
        PageRenderer,
        PageSnapshot,
        PlaywrightRenderer,
        RenderMode,
        UrllibHTTPTransport,
    )
    from .crawl import (
        CrawlDiscoveryResult,
        CrawlFailure,
        CrawlLink,
        CrawlPageRecord,
        CrawlPolicy,
        RelevanceEvidence,
        TargetPageAssessment,
        TargetPageClassifier,
        TargetPageDiscoveryResult,
        TargetPagePolicy,
        TargetPageStatus,
        URLDiscoveryCrawler,
    )
    from .engine import (
        AttributeProvider,
        AttributeRecordProvider,
        AutoDiscoveryProvider,
        Candidate,
        Evidence,
        ExtractionEngine,
        ExtractionResult,
        FieldDecision,
        FieldSpec,
        FieldStatus,
        JSONLDRecordProvider,
        MultiRecordExtractionEngine,
        RawAsset,
        RecordBoundary,
        RecordBoundaryStatus,
        RecordExtractionResult,
        RecordProvider,
        RecordProviderResult,
        RecordSetResult,
        RecordStatus,
        make_record_id,
    )
    from .execution import (
        JOB_CHECKPOINT_VERSION,
        ExtractionJob,
        InMemoryJobCheckpointStore,
        JobCheckpointMismatchError,
        JobCheckpointStore,
        JobExecutor,
        JobItem,
        JobItemStatus,
        JobRunResult,
        JobStatus,
        JsonJobCheckpointStore,
        RetryPolicy,
    )
    from .orchestration import URLExtractionPipeline, URLExtractionResult
    from .profile_lifecycle import (
        PROFILE_SCHEMA_VERSION,
        InMemorySiteProfileStore,
        JsonSiteProfileStore,
        ProfileLifecyclePolicy,
        ProfilePruneReport,
        SQLiteSiteProfileStore,
        SiteProfileStore,
    )
    from .profiles import (
        ConfirmationLearner,
        EvidenceFingerprint,
        LearningEvent,
        LearningPolicy,
        ProfileAwareProvider,
        ProfileSignalStats,
        candidate_fingerprints,
        site_key_from_url,
    )
    from .recovery import ExtractionQuality, SemanticRecoveryPolicy
    from .results import (
        MULTI_RECORD_RESULT_SCHEMA_VERSION,
        RESULT_SCHEMA_VERSION,
        DurableRecordReviewCoordinator,
        InMemoryResultStore,
        JsonResultStore,
        RecordResultCodec,
        RecordResultRepository,
        RecordReviewUpdate,
        RecordSetManifest,
        ResultCodec,
        ResultConflictError,
        ResultDefinitionMismatchError,
        ResultIntegrityError,
        ResultNotFoundError,
        ResultPersistenceError,
        ResultRepository,
        ResultSerializationError,
        ResultStore,
        SQLiteResultStore,
        StoredRecordResult,
        StoredResultRecord,
        StoredResultStatus,
        parse_record_storage_item_id,
        record_set_storage_item_id,
        record_storage_item_id,
    )
    from .results.review import DurableReviewCoordinator, ReviewUpdate
    from .review_queue import (
        REVIEW_QUEUE_SCHEMA_VERSION,
        GovernedRecordReviewQueue,
        GovernedReviewQueue,
        InMemoryReviewQueueStore,
        JsonReviewQueueStore,
        RecordReviewClaim,
        RecordReviewQueueItem,
        RecordReviewSubmission,
        ReviewAction,
        ReviewAuditEvent,
        ReviewClaim,
        ReviewLease,
        ReviewLeaseConflictError,
        ReviewLeaseExpiredError,
        ReviewLeaseNotFoundError,
        ReviewQueueError,
        ReviewQueueItem,
        ReviewQueueStore,
        ReviewerIdentity,
        ReviewerMismatchError,
        ReviewSubmission,
        SQLiteReviewQueueStore,
    )

__all__ = [
    'JOB_CHECKPOINT_VERSION',
    'MULTI_RECORD_RESULT_SCHEMA_VERSION',
    'PROFILE_SCHEMA_VERSION',
    'RESULT_SCHEMA_VERSION',
    'REVIEW_QUEUE_SCHEMA_VERSION',
    'AcquisitionAttempt',
    'AcquisitionEngine',
    'AcquisitionError',
    'AcquisitionRequest',
    'AcquisitionResult',
    'AttributeProvider',
    'AttributeRecordProvider',
    'AutoDiscoveryProvider',
    'Candidate',
    'ConfirmationLearner',
    'CrawlDiscoveryResult',
    'CrawlFailure',
    'CrawlLink',
    'CrawlPageRecord',
    'CrawlPolicy',
    'DefaultRenderPolicy',
    'DurableRecordReviewCoordinator',
    'DurableReviewCoordinator',
    'Evidence',
    'EvidenceFingerprint',
    'ExtractionEngine',
    'ExtractionJob',
    'ExtractionQuality',
    'ExtractionResult',
    'FieldDecision',
    'FieldSpec',
    'FieldStatus',
    'GovernedRecordReviewQueue',
    'GovernedReviewQueue',
    'HTTPTransport',
    'InMemoryJobCheckpointStore',
    'InMemoryResultStore',
    'InMemoryReviewQueueStore',
    'InMemorySiteProfileStore',
    'JSONLDRecordProvider',
    'JobCheckpointMismatchError',
    'JobCheckpointStore',
    'JobExecutor',
    'JobItem',
    'JobItemStatus',
    'JobRunResult',
    'JobStatus',
    'JsonJobCheckpointStore',
    'JsonResultStore',
    'JsonReviewQueueStore',
    'JsonSiteProfileStore',
    'LearningEvent',
    'LearningPolicy',
    'MissingBrowserDependencyError',
    'MultiRecordExtractionEngine',
    'PageRenderer',
    'PageSnapshot',
    'PlaywrightRenderer',
    'ProfileAwareProvider',
    'ProfileLifecyclePolicy',
    'ProfilePruneReport',
    'ProfileSignalStats',
    'RawAsset',
    'RecordBoundary',
    'RecordBoundaryStatus',
    'RecordExtractionResult',
    'RecordProvider',
    'RecordProviderResult',
    'RecordResultCodec',
    'RecordResultRepository',
    'RecordReviewClaim',
    'RecordReviewQueueItem',
    'RecordReviewSubmission',
    'RecordReviewUpdate',
    'RecordSetManifest',
    'RecordSetResult',
    'RecordStatus',
    'RelevanceEvidence',
    'RenderMode',
    'ResultCodec',
    'ResultConflictError',
    'ResultDefinitionMismatchError',
    'ResultIntegrityError',
    'ResultNotFoundError',
    'ResultPersistenceError',
    'ResultRepository',
    'ResultSerializationError',
    'ResultStore',
    'RetryPolicy',
    'ReviewAction',
    'ReviewAuditEvent',
    'ReviewClaim',
    'ReviewLease',
    'ReviewLeaseConflictError',
    'ReviewLeaseExpiredError',
    'ReviewLeaseNotFoundError',
    'ReviewQueueError',
    'ReviewQueueItem',
    'ReviewQueueStore',
    'ReviewerIdentity',
    'ReviewerMismatchError',
    'ReviewSubmission',
    'ReviewUpdate',
    'SQLiteResultStore',
    'SQLiteReviewQueueStore',
    'SQLiteSiteProfileStore',
    'SemanticRecoveryPolicy',
    'SiteProfileStore',
    'StoredRecordResult',
    'StoredResultRecord',
    'StoredResultStatus',
    'TargetPageAssessment',
    'TargetPageClassifier',
    'TargetPageDiscoveryResult',
    'TargetPagePolicy',
    'TargetPageStatus',
    'URLDiscoveryCrawler',
    'URLExtractionPipeline',
    'URLExtractionResult',
    'UrllibHTTPTransport',
    'candidate_fingerprints',
    'make_record_id',
    'parse_record_storage_item_id',
    'record_set_storage_item_id',
    'record_storage_item_id',
    'site_key_from_url',
]

_EXPORT_MODULES = {
    'AcquisitionAttempt': '.acquisition',
    'AcquisitionEngine': '.acquisition',
    'AcquisitionError': '.acquisition',
    'AcquisitionRequest': '.acquisition',
    'AcquisitionResult': '.acquisition',
    'AttributeProvider': '.engine',
    'AttributeRecordProvider': '.engine',
    'AutoDiscoveryProvider': '.engine',
    'Candidate': '.engine',
    'ConfirmationLearner': '.profiles',
    'CrawlDiscoveryResult': '.crawl',
    'CrawlFailure': '.crawl',
    'CrawlLink': '.crawl',
    'CrawlPageRecord': '.crawl',
    'CrawlPolicy': '.crawl',
    'DefaultRenderPolicy': '.acquisition',
    'DurableRecordReviewCoordinator': '.results',
    'DurableReviewCoordinator': '.results.review',
    'Evidence': '.engine',
    'EvidenceFingerprint': '.profiles',
    'ExtractionEngine': '.engine',
    'ExtractionJob': '.execution',
    'ExtractionQuality': '.recovery',
    'ExtractionResult': '.engine',
    'FieldDecision': '.engine',
    'FieldSpec': '.engine',
    'FieldStatus': '.engine',
    'GovernedRecordReviewQueue': '.review_queue',
    'GovernedReviewQueue': '.review_queue',
    'HTTPTransport': '.acquisition',
    'InMemoryJobCheckpointStore': '.execution',
    'InMemoryResultStore': '.results',
    'InMemoryReviewQueueStore': '.review_queue',
    'InMemorySiteProfileStore': '.profile_lifecycle',
    'JOB_CHECKPOINT_VERSION': '.execution',
    'JSONLDRecordProvider': '.engine',
    'JobCheckpointMismatchError': '.execution',
    'JobCheckpointStore': '.execution',
    'JobExecutor': '.execution',
    'JobItem': '.execution',
    'JobItemStatus': '.execution',
    'JobRunResult': '.execution',
    'JobStatus': '.execution',
    'JsonJobCheckpointStore': '.execution',
    'JsonResultStore': '.results',
    'JsonReviewQueueStore': '.review_queue',
    'JsonSiteProfileStore': '.profile_lifecycle',
    'LearningEvent': '.profiles',
    'LearningPolicy': '.profiles',
    'MULTI_RECORD_RESULT_SCHEMA_VERSION': '.results',
    'MissingBrowserDependencyError': '.acquisition',
    'MultiRecordExtractionEngine': '.engine',
    'PROFILE_SCHEMA_VERSION': '.profile_lifecycle',
    'PageRenderer': '.acquisition',
    'PageSnapshot': '.acquisition',
    'PlaywrightRenderer': '.acquisition',
    'ProfileAwareProvider': '.profiles',
    'ProfileLifecyclePolicy': '.profile_lifecycle',
    'ProfilePruneReport': '.profile_lifecycle',
    'ProfileSignalStats': '.profiles',
    'RESULT_SCHEMA_VERSION': '.results',
    'REVIEW_QUEUE_SCHEMA_VERSION': '.review_queue',
    'RawAsset': '.engine',
    'RecordBoundary': '.engine',
    'RecordBoundaryStatus': '.engine',
    'RecordExtractionResult': '.engine',
    'RecordProvider': '.engine',
    'RecordProviderResult': '.engine',
    'RecordResultCodec': '.results',
    'RecordResultRepository': '.results',
    'RecordReviewClaim': '.review_queue',
    'RecordReviewQueueItem': '.review_queue',
    'RecordReviewSubmission': '.review_queue',
    'RecordReviewUpdate': '.results',
    'RecordSetManifest': '.results',
    'RecordSetResult': '.engine',
    'RecordStatus': '.engine',
    'RelevanceEvidence': '.crawl',
    'RenderMode': '.acquisition',
    'ResultCodec': '.results',
    'ResultConflictError': '.results',
    'ResultDefinitionMismatchError': '.results',
    'ResultIntegrityError': '.results',
    'ResultNotFoundError': '.results',
    'ResultPersistenceError': '.results',
    'ResultRepository': '.results',
    'ResultSerializationError': '.results',
    'ResultStore': '.results',
    'RetryPolicy': '.execution',
    'ReviewAction': '.review_queue',
    'ReviewAuditEvent': '.review_queue',
    'ReviewClaim': '.review_queue',
    'ReviewLease': '.review_queue',
    'ReviewLeaseConflictError': '.review_queue',
    'ReviewLeaseExpiredError': '.review_queue',
    'ReviewLeaseNotFoundError': '.review_queue',
    'ReviewQueueError': '.review_queue',
    'ReviewQueueItem': '.review_queue',
    'ReviewQueueStore': '.review_queue',
    'ReviewSubmission': '.review_queue',
    'ReviewUpdate': '.results.review',
    'ReviewerIdentity': '.review_queue',
    'ReviewerMismatchError': '.review_queue',
    'SQLiteResultStore': '.results',
    'SQLiteReviewQueueStore': '.review_queue',
    'SQLiteSiteProfileStore': '.profile_lifecycle',
    'SemanticRecoveryPolicy': '.recovery',
    'SiteProfileStore': '.profile_lifecycle',
    'StoredRecordResult': '.results',
    'StoredResultRecord': '.results',
    'StoredResultStatus': '.results',
    'TargetPageAssessment': '.crawl',
    'TargetPageClassifier': '.crawl',
    'TargetPageDiscoveryResult': '.crawl',
    'TargetPagePolicy': '.crawl',
    'TargetPageStatus': '.crawl',
    'URLDiscoveryCrawler': '.crawl',
    'URLExtractionPipeline': '.orchestration',
    'URLExtractionResult': '.orchestration',
    'UrllibHTTPTransport': '.acquisition',
    'candidate_fingerprints': '.profiles',
    'make_record_id': '.engine',
    'parse_record_storage_item_id': '.results',
    'record_set_storage_item_id': '.results',
    'record_storage_item_id': '.results',
    'site_key_from_url': '.profiles',
}


def __getattr__(name: str):
    """Load public symbols on first access without changing their identity."""
    module = _EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_import_module(module, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
