from .client import DataPlatformClient, DataPlatformError, DataPlatformHttpClient
from .models import (
    Collection,
    CollectionStats,
    ConsumerContract,
    DiscoveredResource,
    DiscoveryResponse,
    Entity,
    EntityAlias,
    EntityAliasInput,
    EntityRelation,
    EntityResolveResponse,
    IngestResult,
    ProcessedChunk,
    ProcessedDocument,
    SearchEvidence,
    SearchHit,
    SearchResponse,
    SearchScores,
)

__all__ = [
    "Collection",
    "CollectionStats",
    "ConsumerContract",
    "DataPlatformClient",
    "DataPlatformError",
    "DataPlatformHttpClient",
    "DiscoveredResource",
    "DiscoveryResponse",
    "Entity",
    "EntityAlias",
    "EntityAliasInput",
    "EntityRelation",
    "EntityResolveResponse",
    "IngestResult",
    "ProcessedChunk",
    "ProcessedDocument",
    "SearchEvidence",
    "SearchHit",
    "SearchResponse",
    "SearchScores",
]
